export const LOGIN_KEY = "LOGIN_KEY";
export const SIGNUP_KEY = "SIGNUP_KEY";
export const CREATE_PROSPECT_KEY = "CREATE_PROSPECT_KEY";
export const FETCH_ALL_PROSPECTS_KEY = "FETCH_ALL_PROSPECTS_KEY";
export const FETCH_PROSPECTS_KEY = "FETCH_PROSPECTS_KEY";

// OFFER
export const FETCH_ALL_OFFER_KEY = "FETCH_ALL_OFFER_KEY";
export const FETCH_OFFER_KEY = "FETCH_OFFER_KEY";
export const CREATE_OFFER_KEY = "CREATE_OFFER_KEY";

// EVENT
export const FETCH_ALL_EVENT_KEY = "FETCH_ALL_EVENT_KEY";
export const CREATE_EVENT_KEY = "CREATE_EVENT_KEY";

// CONTRACT
export const CREATE_CONTRACT_KEY = "CREATE_CONTRACT_KEY";
export const FETCH_ALL_CONTRACT_KEY = "FETCH_ALL_CONTRACT_KEY";
export const FETCH_CONTRACT_KEY = "FETCH_CONTRACT_KEY";

// INVOICE
export const FETCH_ALL_INVOICE_KEY = "FETCH_ALL_INVOICE_KEY";
export const FETCH_INVOICE_KEY = "FETCH_INVOICE_KEY";
