
export const allProspects = [
  {
    prospect_id: "j948fuvdi",
    date: "12 April 2023, 12:43 AM",
    client: "Okinda Peters",
    source: "Offline",
    status: "Pending",
    clientDetails: {
      client: 'Okinda Peters',
      // clientType,
      // phoneNumber,
      // emailAddress,

    },
    // eventDetails:{
    //   eventName,
    //   eventType,
    //   eventDate,
    //   eventLocation,
    //   locationType,

    // },
    // EventSpecification:{
    //   theme,
    //   specifications: [
    //     {
    //       type,
    //       provision,
    //       description,
    //       exhibitorName,
    //       startDate,
    //       endDate,
    //       amount,
    //     }
    //   ]
    // },

  },
  {
    prospect_id: "oyoinuy8r",
    date: "12 April 2023, 12:43 AM",
    client: "James Oshiomole",
    source: "Offline",
    status: "Converted",
    clientDetails: {
      client: 'Okinda Peters',
      // clientType,
      // phoneNumber,
      // emailAddress,

    },
  },
  {
    prospect_id: "orh85l3tp",
    date: "12 April 2023, 12:43 AM",
    client: "Okinda Peters",
    source: "Offline",
    status: "Pending",
     clientDetails: {
      client: 'Okinda Peters',
      // clientType,
      // phoneNumber,
      // emailAddress,

    },
  },
  {
    prospect_id: "98rg54o99",
    date: "12 April 2023, 12:43 AM",
    client: "James Oshiomole",
    source: "Online",
    status: "Converted",
  },
  {
    prospect_id: "noy8f79c7",
    date: "12 April 2023, 12:43 AM",
    client: "James Oshiomole",
    source: "Online",
    status: "Pending",
     clientDetails: {
      client: 'Okinda Peters',
      // clientType,
      // phoneNumber,
      // emailAddress,

    },
  },
  {
    prospect_id: "iu907087t",
    date: "12 April 2023, 12:43 AM",
    client: "James Oshiomole",
    source: "Offline",
    status: "Converted",
     clientDetails: {
      client: 'Okinda Peters',
      // clientType,
      // phoneNumber,
      // emailAddress,

    },
  },
  {
    prospect_id: "7liuu8ny",
    date: "12 April 2023, 12:43 AM",
    client: "Okinda Peters",
    source: "Offline",
    status: "Converted",
     clientDetails: {
      client: 'Okinda Peters',
      // clientType,
      // phoneNumber,
      // emailAddress,

    },
  },
  {
    prospect_id: "ysghwrh74",
    date: "12 April 2023, 12:43 AM",
    client: "James Oshiomole",
    source: "Online",
    status: "Converted",
     clientDetails: {
      client: 'Okinda Peters',
      // clientType,
      // phoneNumber,
      // emailAddress,

    },
  },
  {
    prospect_id: "09yu75x76",
    date: "12 April 2023, 12:43 AM",
    client: "James Oshiomole",
    source: "Offline",
    status: "Converted",
     clientDetails: {
      client: 'Okinda Peters',
      // clientType,
      // phoneNumber,
      // emailAddress,

    },
  },
  {
    prospect_id: "aev6t9887",
    date: "12 April 2023, 12:43 AM",
    client: "James Oshiomole",
    source: "Offline",
    status: "Converted",
     clientDetails: {
      client: 'Okinda Peters',
      // clientType,
      // phoneNumber,
      // emailAddress,

    },
  },
  {
    prospect_id: "rc867x854",
    date: "12 April 2023, 12:43 AM",
    client: "Okinda Peters",
    source: "Offline",
    status: "Pending",
     clientDetails: {
      client: 'Okinda Peters',
      // clientType,
      // phoneNumber,
      // emailAddress,

    },
  },
  {
    prospect_id: "loidx79dd",
    date: "12 April 2023, 12:43 AM",
    client: "James Oshiomole",
    source: "Online",
    status: "Pending",
     clientDetails: {
      client: 'Okinda Peters',
      // clientType,
      // phoneNumber,
      // emailAddress,

    },
  },
  {
    prospect_id: "cr97754xy",
    date: "12 April 2023, 12:43 AM",
    client: "James Oshiomole",
    source: "Online",
    status: "Converted",
     clientDetails: {
      client: 'Okinda Peters',
      // clientType,
      // phoneNumber,
      // emailAddress,

    },
  },
  {
    prospect_id: "959c98970",
    date: "12 April 2023, 12:43 AM",
    client: "James Oshiomole",
    source: "Offline",
    status: "Converted",
     clientDetails: {
      client: 'Okinda Peters',
      // clientType,
      // phoneNumber,
      // emailAddress,

    },
  },
];
export const allContracts = [
  {
    prospect_id: "tsszyh-tt",
    date: "12 April 2023, 12:43 AM",
    client: "Okinda Peters",
    location: "No 17 Raleway Street, Ogudu",
    status: "Pending",
  },
  {
    prospect_id: "uitrafszy",
    date: "12 April 2023, 12:43 AM",
    client: "James Oshiomole",
    location: "No 17 Raleway Street, Ogudu",
    status: "Accepted",
  },
  {
    prospect_id: "7z765tob7",
    date: "12 April 2023, 12:43 AM",
    client: "Okinda Peters",
    location: "No 17 Raleway Street, Ogudu",
    status: "Pending",
  },
  {
    prospect_id: "bddsar37",
    date: "12 April 2023, 12:43 AM",
    client: "James Oshiomole",
    location: "No 17 Raleway Street, Ogudu",
    status: "Accepted",
  },
  {
    prospect_id: "yx3e8ubt",
    date: "12 April 2023, 12:43 AM",
    client: "James Oshiomole",
    location: "No 17 Raleway Street, Ogudu",
    status: "Accepted",
  },
  {
    prospect_id: "r3zs7cvui",
    date: "12 April 2023, 12:43 AM",
    client: "James Oshiomole",
    location: "No 17 Raleway Street, Ogudu",
    status: "Accepted",
  },
  {
    prospect_id: "utdfej59",
    date: "12 April 2023, 12:43 AM",
    client: "Okinda Peters",
    location: "No 17 Raleway Street, Ogudu",
    status: "Pending",
  },
  {
    prospect_id: "ys6tjhnjj",
    date: "12 April 2023, 12:43 AM",
    client: "James Oshiomole",
    location: "No 17 Raleway Street, Ogudu",
    status: "Accepted",
  },
  {
    prospect_id: "tubiy6d86",
    date: "12 April 2023, 12:43 AM",
    client: "James Oshiomole",
    location: "No 17 Raleway Street, Ogudu",
    status: "Accepted",
  },
  {
    prospect_id: "rtwrbyn446",
    date: "12 April 2023, 12:43 AM",
    client: "James Oshiomole",
    location: "No 17 Raleway Street, Ogudu",
    status: "Accepted",
  },
  {
    prospect_id: "tnyn257nr",
    date: "12 April 2023, 12:43 AM",
    client: "Okinda Peters",
    location: "No 17 Raleway Street, Ogudu",
    status: "Accepted",
  },
  {
    prospect_id: "d6r9r9,m",
    date: "12 April 2023, 12:43 AM",
    client: "James Oshiomole",
    location: "No 17 Raleway Street, Ogudu",
    status: "Accepted",
  },
  {
    prospect_id: 'hdu67rmtol',
    date: "12 April 2023, 12:43 AM",
    client: "James Oshiomole",
    location: "No 17 Raleway Street, Ogudu",
    status: "Accepted",
  },
  {
    prospect_id: 'u55emnl7u',
    date: "12 April 2023, 12:43 AM",
    client: "James Oshiomole",
    location: "No 17 Raleway Street, Ogudu",
    status: "Accepted",
  },
];
export const allPayments = [
  {
    prospect_id: 'pujjpu-uh',
    date: "12 April 2023, 12:43 AM",
    client: "Okinda Peters",
    location: "No 17 Raleway Street, Ogudu",
    status: "Pending",
  },
  {
    prospect_id: 'zes755o8',
    date: "12 April 2023, 12:43 AM",
    client: "James Oshiomole",
    location: "No 17 Raleway Street, Ogudu",
    status: "Accepted",
  },
  {
    prospect_id: 'rtybbn6i35',
    date: "12 April 2023, 12:43 AM",
    client: "Okinda Peters",
    location: "No 17 Raleway Street, Ogudu",
    status: "Pending",
  },
  {
    prospect_id: '5767n556n',
    date: "12 April 2023, 12:43 AM",
    client: "James Oshiomole",
    location: "No 17 Raleway Street, Ogudu",
    status: "Accepted",
  },
  {
    prospect_id: 'i6hy9rtft',
    date: "12 April 2023, 12:43 AM",
    client: "James Oshiomole",
    location: "No 17 Raleway Street, Ogudu",
    status: "Accepted",
  },
  {
    prospect_id: 'u-utdmvg',
    date: "12 April 2023, 12:43 AM",
    client: "James Oshiomole",
    location: "No 17 Raleway Street, Ogudu",
    status: "Accepted",
  },
  {
    prospect_id: '6vrcrfnmrt ',
    date: "12 April 2023, 12:43 AM",
    client: "Okinda Peters",
    location: "No 17 Raleway Street, Ogudu",
    status: "Pending",
  },
  {
    prospect_id: '465ertgnr',
    date: "12 April 2023, 12:43 AM",
    client: "James Oshiomole",
    location: "No 17 Raleway Street, Ogudu",
    status: "Accepted",
  },
  {
    prospect_id: 'uyfdgtgth',
    date: "12 April 2023, 12:43 AM",
    client: "James Oshiomole",
    location: "No 17 Raleway Street, Ogudu",
    status: "Accepted",
  },
  {
    prospect_id: '866tgnr5f',
    date: "12 April 2023, 12:43 AM",
    client: "James Oshiomole",
    location: "No 17 Raleway Street, Ogudu",
    status: "Accepted",
  },
  {
    prospect_id: '6rytyh445',
    date: "12 April 2023, 12:43 AM",
    client: "Okinda Peters",
    location: "No 17 Raleway Street, Ogudu",
    status: "Accepted",
  },
  {
    prospect_id: '57rtye4t',
    date: "12 April 2023, 12:43 AM",
    client: "James Oshiomole",
    location: "No 17 Raleway Street, Ogudu",
    status: "Accepted",
  },
  {
    prospect_id: 'u6ghty55r',
    date: "12 April 2023, 12:43 AM",
    client: "James Oshiomole",
    location: "No 17 Raleway Street, Ogudu",
    status: "Accepted",
  },
  {
    prospect_id: '6thr566yt',
    date: "12 April 2023, 12:43 AM",
    client: "James Oshiomole",
    location: "No 17 Raleway Street, Ogudu",
    status: "Accepted",
  },
];

export const allEvents = [
  {
    coverArt: "/images/dashboard/default.png",
    eventDate: "17 May, 2023",
    eventName: "The VAGS Wedding",
    provision: "Society & Culture",
    frequency: "One time",
    payments: "1/3 Payments",
    specification: "3/3 specifications",
    passes: "20 persons",
    date: "2 days ago",
  },
  {
    coverArt: "/images/dashboard/default.png",
    eventDate: "17 May, 2023",
    eventName: "The VAGS Wedding",
    provision: "Society & Culture",
    frequency: "One time",
    specification: "3/3 specifications",
    payments: "1/3 Payments",
    passes: "20 persons",
    date: "2 days ago",
  },
  {
    coverArt: "/images/dashboard/default.png",
    eventDate: "17 May, 2023",
    eventName: "The VAGS Wedding",
    provision: "Society & Culture",
    frequency: "One time",
    payments: "1/3 Payments",
    specification: "3/3 specifications",
    passes: "20 persons",
    date: "2 days ago",
  },
  {
    coverArt: "/images/dashboard/default.png",
    eventDate: "17 May, 2023",
    eventName: "The VAGS Wedding",
    provision: "Society & Culture",
    frequency: "One time",
    specification: "3/3 specifications",
    payments: "1/3 Payments",
    passes: "20 persons",
    date: "2 days ago",
  },
  {
    coverArt: "/images/dashboard/default.png",
    eventDate: "17 May, 2023",
    eventName: "The VAGS Wedding",
    provision: "Society & Culture",
    frequency: "One time",
    specification: "3/3 specifications",
    payments: "1/3 Payments",
    passes: "20 persons",
    date: "2 days ago",
  },
];

export const allEntry = [
  {
    coverArt: "/images/dashboard/default.png",
    eventDate: "17 May, 2023",
    eventName: "The VAGS Wedding",
    provision: "Early bird",
    frequency: "Limited",
    specification: "Paid",
    passes: "$200.00",
    payments: "200 Passes",
    date: "2 days ago",
  },
  {
    coverArt: "/images/dashboard/default.png",
    eventDate: "17 May, 2023",
    eventName: "The VAGS Wedding",
    provision: "Early bird",
    frequency: "Limited",
    passes: "N/A",
    specification: "Free",
    payments: "200 Passes",
    date: "2 days ago",
  },
  {
    coverArt: "/images/dashboard/default.png",
    eventDate: "17 May, 2023",
    eventName: "The VAGS Wedding",
    provision: "Early bird",
    frequency: "Limited",
    specification: "Invite only",
    passes: "$200.00",
    payments: "200 Passes",
    date: "2 days ago",
  },
  {
    coverArt: "/images/dashboard/default.png",
    eventDate: "17 May, 2023",
    eventName: "The VAGS Wedding",
    provision: "Early bird",
    frequency: "Limited",
    specification: "Free",
    passes: "N/A",
    payments: "200 Passes",
    date: "2 days ago",
  },
  {
    coverArt: "/images/dashboard/default.png",
    eventDate: "17 May, 2023",
    eventName: "The VAGS Wedding",
    provision: "Early bird",
    frequency: "Limited",
    specification: "Invite only",
    passes: "1/3",
    payments: "200 Passes",
    date: "2 days ago",
  },
];
